// Package pdf provides a high-level stateful wrapper for Fitz and MuPDF. It wraps C-bindings
// autogenerated from MuPDF headers, located at sphere.software/pdf-go/mupdf, making the API easy to use
// in everyday tasks.
package pdf
