// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 11 Oct 2017 01:43:23 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "mupdf/pdf.h"
#include "mupdf/fitz.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// fz_tune_image_decode_fn_4232b35a is a proxy for callback fz_tune_image_decode_fn.
void fz_tune_image_decode_fn_4232b35a(void* arg, int w, int h, int l2factor, fz_irect* subarea);

// fz_tune_image_scale_fn_1989219 is a proxy for callback fz_tune_image_scale_fn.
int fz_tune_image_scale_fn_1989219(void* arg, int dst_w, int dst_h, int src_w, int src_h);

// fz_hash_table_drop_fn_7865ac47 is a proxy for callback fz_hash_table_drop_fn.
void fz_hash_table_drop_fn_7865ac47(fz_context* ctx, void* val);

// fz_hash_table_for_each_fn_af0d233f is a proxy for callback fz_hash_table_for_each_fn.
void fz_hash_table_for_each_fn_af0d233f(fz_context* ctx, void* state, void* key, int keylen, void* val);

// fz_output_write_fn_69b8337c is a proxy for callback fz_output_write_fn.
void fz_output_write_fn_69b8337c(fz_context* ctx, void* state, void* data, unsigned long int n);

// fz_output_seek_fn_bf2e2bed is a proxy for callback fz_output_seek_fn.
void fz_output_seek_fn_bf2e2bed(fz_context* ctx, void* state, int offset, int whence);

// fz_output_tell_fn_ea4e4fab is a proxy for callback fz_output_tell_fn.
int fz_output_tell_fn_ea4e4fab(fz_context* ctx, void* state);

// fz_output_close_fn_c2d1d433 is a proxy for callback fz_output_close_fn.
void fz_output_close_fn_c2d1d433(fz_context* ctx, void* state);

// fz_bidi_fragment_fn_f6d4b809 is a proxy for callback fz_bidi_fragment_fn.
void fz_bidi_fragment_fn_f6d4b809(unsigned int* fragment, unsigned long int fragmentLen, int bidiLevel, int script, void* arg);

// fz_stream_next_fn_a646ae0c is a proxy for callback fz_stream_next_fn.
int fz_stream_next_fn_a646ae0c(fz_context* ctx, fz_stream* stm, unsigned long int max);

// fz_stream_close_fn_af835bb4 is a proxy for callback fz_stream_close_fn.
void fz_stream_close_fn_af835bb4(fz_context* ctx, void* state);

// fz_stream_seek_fn_304547f8 is a proxy for callback fz_stream_seek_fn.
void fz_stream_seek_fn_304547f8(fz_context* ctx, fz_stream* stm, int offset, int whence);

// fz_stream_meta_fn_3599fe3d is a proxy for callback fz_stream_meta_fn.
int fz_stream_meta_fn_3599fe3d(fz_context* ctx, fz_stream* stm, int key, int size, void* ptr);

// fz_store_drop_fn_aab4a233 is a proxy for callback fz_store_drop_fn.
void fz_store_drop_fn_aab4a233(fz_context* arg0, fz_storable* arg1);

// fz_store_filter_fn_a0da2df9 is a proxy for callback fz_store_filter_fn.
int fz_store_filter_fn_a0da2df9(fz_context* ctx, void* arg, void* key);

// fz_colorspace_convert_fn_c5345ee1 is a proxy for callback fz_colorspace_convert_fn.
void fz_colorspace_convert_fn_c5345ee1(fz_context* ctx, fz_colorspace* cs, float* src, float* dst);

// fz_colorspace_destruct_fn_779fc731 is a proxy for callback fz_colorspace_destruct_fn.
void fz_colorspace_destruct_fn_779fc731(fz_context* ctx, fz_colorspace* cs);

// fz_colorspace_base_fn_eba67be4 is a proxy for callback fz_colorspace_base_fn.
fz_colorspace* fz_colorspace_base_fn_eba67be4(fz_colorspace* cs);

// fz_colorspace_clamp_fn_17a541b8 is a proxy for callback fz_colorspace_clamp_fn.
void fz_colorspace_clamp_fn_17a541b8(fz_colorspace* cs, float* src, float* dst);

// fz_pixmap_converter_a63960a is a proxy for callback fz_pixmap_converter.
void fz_pixmap_converter_a63960a(fz_context* ctx, fz_pixmap* dp, fz_pixmap* sp, fz_colorspace* prf, fz_default_colorspaces* default_cs, fz_color_params* color_params, int copy_spots);

// fz_drop_image_fn_37d8be50 is a proxy for callback fz_drop_image_fn.
void fz_drop_image_fn_37d8be50(fz_context* ctx, fz_image* image);

// fz_image_get_pixmap_fn_e97ee8eb is a proxy for callback fz_image_get_pixmap_fn.
fz_pixmap* fz_image_get_pixmap_fn_e97ee8eb(fz_context* ctx, fz_image* im, fz_irect* subarea, int w, int h, int* l2factor);

// fz_image_get_size_fn_7202727c is a proxy for callback fz_image_get_size_fn.
unsigned long int fz_image_get_size_fn_7202727c(fz_context* arg0, fz_image* arg1);

// fz_shade_prepare_fn_6a663594 is a proxy for callback fz_shade_prepare_fn.
void fz_shade_prepare_fn_6a663594(fz_context* ctx, void* arg, fz_vertex* v, float* c);

// fz_shade_process_fn_7e13ccea is a proxy for callback fz_shade_process_fn.
void fz_shade_process_fn_7e13ccea(fz_context* ctx, void* arg, fz_vertex* av, fz_vertex* bv, fz_vertex* cv);

// fz_load_system_font_fn_cf2c657 is a proxy for callback fz_load_system_font_fn.
fz_font* fz_load_system_font_fn_cf2c657(fz_context* ctx, char* name, int bold, int italic, int needs_exact_metrics);

// fz_load_system_cjk_font_fn_b491fed9 is a proxy for callback fz_load_system_cjk_font_fn.
fz_font* fz_load_system_cjk_font_fn_b491fed9(fz_context* ctx, char* name, int ros, int serif);

// fz_load_system_fallback_font_fn_36cb0cb is a proxy for callback fz_load_system_fallback_font_fn.
fz_font* fz_load_system_fallback_font_fn_36cb0cb(fz_context* ctx, int script, int language, int serif, int bold, int italic);

// fz_cmm_new_instance_fn_3bc12687 is a proxy for callback fz_cmm_new_instance_fn.
fz_cmm_instance* fz_cmm_new_instance_fn_3bc12687(fz_context* ctx);

// fz_cmm_drop_instance_fn_8fce668 is a proxy for callback fz_cmm_drop_instance_fn.
void fz_cmm_drop_instance_fn_8fce668(fz_cmm_instance* instance);

// fz_cmm_transform_pixmap_fn_a9ad9719 is a proxy for callback fz_cmm_transform_pixmap_fn.
void fz_cmm_transform_pixmap_fn_a9ad9719(fz_cmm_instance* ctx, fz_icclink* link, fz_pixmap* dst, fz_pixmap* src);

// fz_cmm_transform_color_fn_1cd2d69f is a proxy for callback fz_cmm_transform_color_fn.
void fz_cmm_transform_color_fn_1cd2d69f(fz_cmm_instance* ctx, fz_icclink* link, unsigned short int* dst, unsigned short int* src);

// fz_cmm_init_link_fn_2c234a07 is a proxy for callback fz_cmm_init_link_fn.
void fz_cmm_init_link_fn_2c234a07(fz_cmm_instance* ctx, fz_icclink* link, fz_iccprofile* dst, int dst_extras, fz_iccprofile* src, int src_extras, fz_iccprofile* prf, fz_color_params* rend, int cmm_flags, int num_bytes, int copy_spots);

// fz_cmm_fin_link_fn_2b624a1a is a proxy for callback fz_cmm_fin_link_fn.
void fz_cmm_fin_link_fn_2b624a1a(fz_cmm_instance* ctx, fz_icclink* link);

// fz_cmm_init_profile_fn_5d5a5731 is a proxy for callback fz_cmm_init_profile_fn.
void fz_cmm_init_profile_fn_5d5a5731(fz_cmm_instance* ctx, fz_iccprofile* profile);

// fz_cmm_fin_profile_fn_487f1613 is a proxy for callback fz_cmm_fin_profile_fn.
void fz_cmm_fin_profile_fn_487f1613(fz_cmm_instance* ctx, fz_iccprofile* profile);

// fz_document_drop_fn_199b99e3 is a proxy for callback fz_document_drop_fn.
void fz_document_drop_fn_199b99e3(fz_context* ctx, fz_document* doc);

// fz_document_needs_password_fn_7840f251 is a proxy for callback fz_document_needs_password_fn.
int fz_document_needs_password_fn_7840f251(fz_context* ctx, fz_document* doc);

// fz_document_authenticate_password_fn_ccf5e3d is a proxy for callback fz_document_authenticate_password_fn.
int fz_document_authenticate_password_fn_ccf5e3d(fz_context* ctx, fz_document* doc, char* password);

// fz_document_has_permission_fn_64826a68 is a proxy for callback fz_document_has_permission_fn.
int fz_document_has_permission_fn_64826a68(fz_context* ctx, fz_document* doc, fz_permission permission);

// fz_document_load_outline_fn_ae85b015 is a proxy for callback fz_document_load_outline_fn.
fz_outline* fz_document_load_outline_fn_ae85b015(fz_context* ctx, fz_document* doc);

// fz_document_layout_fn_cf5eaaa9 is a proxy for callback fz_document_layout_fn.
void fz_document_layout_fn_cf5eaaa9(fz_context* ctx, fz_document* doc, float w, float h, float em);

// fz_document_resolve_link_fn_f25a9656 is a proxy for callback fz_document_resolve_link_fn.
int fz_document_resolve_link_fn_f25a9656(fz_context* ctx, fz_document* doc, char* uri, float* xp, float* yp);

// fz_document_count_pages_fn_20f867e7 is a proxy for callback fz_document_count_pages_fn.
int fz_document_count_pages_fn_20f867e7(fz_context* ctx, fz_document* doc);

// fz_document_load_page_fn_a32c9877 is a proxy for callback fz_document_load_page_fn.
fz_page* fz_document_load_page_fn_a32c9877(fz_context* ctx, fz_document* doc, int number);

// fz_document_lookup_metadata_fn_1f9b8013 is a proxy for callback fz_document_lookup_metadata_fn.
int fz_document_lookup_metadata_fn_1f9b8013(fz_context* ctx, fz_document* doc, char* key, char* buf, int size);

// fz_document_output_intent_fn_3e3b0bcf is a proxy for callback fz_document_output_intent_fn.
fz_colorspace* fz_document_output_intent_fn_3e3b0bcf(fz_context* ctx, fz_document* doc);

// fz_document_make_bookmark_fn_cd7a2755 is a proxy for callback fz_document_make_bookmark_fn.
long int fz_document_make_bookmark_fn_cd7a2755(fz_context* ctx, fz_document* doc, int page);

// fz_document_lookup_bookmark_fn_5171746f is a proxy for callback fz_document_lookup_bookmark_fn.
int fz_document_lookup_bookmark_fn_5171746f(fz_context* ctx, fz_document* doc, long int mark);

// fz_page_drop_page_fn_e86ad7c7 is a proxy for callback fz_page_drop_page_fn.
void fz_page_drop_page_fn_e86ad7c7(fz_context* ctx, fz_page* page);

// fz_page_bound_page_fn_a77bc5ed is a proxy for callback fz_page_bound_page_fn.
fz_rect* fz_page_bound_page_fn_a77bc5ed(fz_context* ctx, fz_page* page, fz_rect* arg2);

// fz_page_run_page_contents_fn_7710be3e is a proxy for callback fz_page_run_page_contents_fn.
void fz_page_run_page_contents_fn_7710be3e(fz_context* ctx, fz_page* page, fz_device* dev, fz_matrix* transform, fz_cookie* cookie);

// fz_page_load_links_fn_40246ac6 is a proxy for callback fz_page_load_links_fn.
fz_link* fz_page_load_links_fn_40246ac6(fz_context* ctx, fz_page* page);

// fz_page_first_annot_fn_96bf83a2 is a proxy for callback fz_page_first_annot_fn.
fz_annot* fz_page_first_annot_fn_96bf83a2(fz_context* ctx, fz_page* page);

// fz_page_page_presentation_fn_4c62d63f is a proxy for callback fz_page_page_presentation_fn.
fz_transition* fz_page_page_presentation_fn_4c62d63f(fz_context* ctx, fz_page* page, fz_transition* transition, float* duration);

// fz_page_control_separation_fn_a66789c6 is a proxy for callback fz_page_control_separation_fn.
void fz_page_control_separation_fn_a66789c6(fz_context* ctx, fz_page* page, int separation, int disable);

// fz_page_separation_disabled_fn_6286727e is a proxy for callback fz_page_separation_disabled_fn.
int fz_page_separation_disabled_fn_6286727e(fz_context* ctx, fz_page* page, int separation);

// fz_page_separations_fn_854f23a7 is a proxy for callback fz_page_separations_fn.
fz_separations* fz_page_separations_fn_854f23a7(fz_context* ctx, fz_page* page);

// fz_annot_drop_fn_30a53795 is a proxy for callback fz_annot_drop_fn.
void fz_annot_drop_fn_30a53795(fz_context* ctx, fz_annot* annot);

// fz_annot_next_fn_d7a4863d is a proxy for callback fz_annot_next_fn.
fz_annot* fz_annot_next_fn_d7a4863d(fz_context* ctx, fz_annot* annot);

// fz_annot_bound_fn_81efb60e is a proxy for callback fz_annot_bound_fn.
fz_rect* fz_annot_bound_fn_81efb60e(fz_context* ctx, fz_annot* annot, fz_rect* rect);

// fz_annot_run_fn_f3ff5201 is a proxy for callback fz_annot_run_fn.
void fz_annot_run_fn_f3ff5201(fz_context* ctx, fz_annot* annot, fz_device* dev, fz_matrix* transform, fz_cookie* cookie);

// fz_document_open_fn_ac22541f is a proxy for callback fz_document_open_fn.
fz_document* fz_document_open_fn_ac22541f(fz_context* ctx, char* filename);

// fz_document_open_with_stream_fn_d625d461 is a proxy for callback fz_document_open_with_stream_fn.
fz_document* fz_document_open_with_stream_fn_d625d461(fz_context* ctx, fz_stream* stream);

// fz_document_recognize_fn_37e0cef4 is a proxy for callback fz_document_recognize_fn.
int fz_document_recognize_fn_37e0cef4(fz_context* ctx, char* magic);

// fz_document_writer_begin_page_fn_67284625 is a proxy for callback fz_document_writer_begin_page_fn.
fz_device* fz_document_writer_begin_page_fn_67284625(fz_context* ctx, fz_document_writer* wri, fz_rect* mediabox);

// fz_document_writer_end_page_fn_c982f24f is a proxy for callback fz_document_writer_end_page_fn.
void fz_document_writer_end_page_fn_c982f24f(fz_context* ctx, fz_document_writer* wri, fz_device* dev);

// fz_document_writer_close_writer_fn_383baadd is a proxy for callback fz_document_writer_close_writer_fn.
void fz_document_writer_close_writer_fn_383baadd(fz_context* ctx, fz_document_writer* wri);

// fz_document_writer_drop_writer_fn_2ac1eb31 is a proxy for callback fz_document_writer_drop_writer_fn.
void fz_document_writer_drop_writer_fn_2ac1eb31(fz_context* ctx, fz_document_writer* wri);

// fz_write_header_fn_60d0d497 is a proxy for callback fz_write_header_fn.
void fz_write_header_fn_60d0d497(fz_context* ctx, fz_band_writer* writer, fz_colorspace* cs);

// fz_write_band_fn_64127b36 is a proxy for callback fz_write_band_fn.
void fz_write_band_fn_64127b36(fz_context* ctx, fz_band_writer* writer, int stride, int band_start, int band_height, unsigned char* samples);

// fz_write_trailer_fn_c6136351 is a proxy for callback fz_write_trailer_fn.
void fz_write_trailer_fn_c6136351(fz_context* ctx, fz_band_writer* writer);

// fz_drop_band_writer_fn_6b3f033f is a proxy for callback fz_drop_band_writer_fn.
void fz_drop_band_writer_fn_6b3f033f(fz_context* ctx, fz_band_writer* writer);

// pdf_doc_event_cb_d9608017 is a proxy for callback pdf_doc_event_cb.
void pdf_doc_event_cb_d9608017(fz_context* ctx, pdf_document* doc, pdf_doc_event* event, void* data);

// pdf_page_contents_process_fn_7f179711 is a proxy for callback pdf_page_contents_process_fn.
void pdf_page_contents_process_fn_7f179711(fz_context* ctx, fz_buffer* buffer, pdf_obj* res, void* arg);

