// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 11 Oct 2017 01:43:23 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void fz_tune_image_decode_fn_4232b35a(void* arg, int w, int h, int l2factor, fz_irect* subarea) {
	fzTuneImageDecodeFn4232B35A(arg, w, h, l2factor, subarea);
}

int fz_tune_image_scale_fn_1989219(void* arg, int dst_w, int dst_h, int src_w, int src_h) {
	return fzTuneImageScaleFn1989219(arg, dst_w, dst_h, src_w, src_h);
}

void fz_hash_table_drop_fn_7865ac47(fz_context* ctx, void* val) {
	fzHashTableDropFn7865AC47(ctx, val);
}

void fz_hash_table_for_each_fn_af0d233f(fz_context* ctx, void* state, void* key, int keylen, void* val) {
	fzHashTableForEachFnAF0D233F(ctx, state, key, keylen, val);
}

void fz_output_write_fn_69b8337c(fz_context* ctx, void* state, void* data, unsigned long int n) {
	fzOutputWriteFn69B8337C(ctx, state, data, n);
}

void fz_output_seek_fn_bf2e2bed(fz_context* ctx, void* state, int offset, int whence) {
	fzOutputSeekFnBF2E2BED(ctx, state, offset, whence);
}

int fz_output_tell_fn_ea4e4fab(fz_context* ctx, void* state) {
	return fzOutputTellFnEA4E4FAB(ctx, state);
}

void fz_output_close_fn_c2d1d433(fz_context* ctx, void* state) {
	fzOutputCloseFnC2D1D433(ctx, state);
}

void fz_bidi_fragment_fn_f6d4b809(unsigned int* fragment, unsigned long int fragmentLen, int bidiLevel, int script, void* arg) {
	fzBidiFragmentFnF6D4B809(fragment, fragmentLen, bidiLevel, script, arg);
}

int fz_stream_next_fn_a646ae0c(fz_context* ctx, fz_stream* stm, unsigned long int max) {
	return fzStreamNextFnA646AE0C(ctx, stm, max);
}

void fz_stream_close_fn_af835bb4(fz_context* ctx, void* state) {
	fzStreamCloseFnAF835BB4(ctx, state);
}

void fz_stream_seek_fn_304547f8(fz_context* ctx, fz_stream* stm, int offset, int whence) {
	fzStreamSeekFn304547F8(ctx, stm, offset, whence);
}

int fz_stream_meta_fn_3599fe3d(fz_context* ctx, fz_stream* stm, int key, int size, void* ptr) {
	return fzStreamMetaFn3599FE3D(ctx, stm, key, size, ptr);
}

void fz_store_drop_fn_aab4a233(fz_context* arg0, fz_storable* arg1) {
	fzStoreDropFnAAB4A233(arg0, arg1);
}

int fz_store_filter_fn_a0da2df9(fz_context* ctx, void* arg, void* key) {
	return fzStoreFilterFnA0DA2DF9(ctx, arg, key);
}

void fz_colorspace_convert_fn_c5345ee1(fz_context* ctx, fz_colorspace* cs, float* src, float* dst) {
	fzColorspaceConvertFnC5345EE1(ctx, cs, src, dst);
}

void fz_colorspace_destruct_fn_779fc731(fz_context* ctx, fz_colorspace* cs) {
	fzColorspaceDestructFn779FC731(ctx, cs);
}

fz_colorspace* fz_colorspace_base_fn_eba67be4(fz_colorspace* cs) {
	return fzColorspaceBaseFnEBA67BE4(cs);
}

void fz_colorspace_clamp_fn_17a541b8(fz_colorspace* cs, float* src, float* dst) {
	fzColorspaceClampFn17A541B8(cs, src, dst);
}

void fz_pixmap_converter_a63960a(fz_context* ctx, fz_pixmap* dp, fz_pixmap* sp, fz_colorspace* prf, fz_default_colorspaces* default_cs, fz_color_params* color_params, int copy_spots) {
	fzPixmapConverterA63960A(ctx, dp, sp, prf, default_cs, color_params, copy_spots);
}

void fz_drop_image_fn_37d8be50(fz_context* ctx, fz_image* image) {
	fzDropImageFn37D8BE50(ctx, image);
}

fz_pixmap* fz_image_get_pixmap_fn_e97ee8eb(fz_context* ctx, fz_image* im, fz_irect* subarea, int w, int h, int* l2factor) {
	return fzImageGetPixmapFnE97EE8EB(ctx, im, subarea, w, h, l2factor);
}

unsigned long int fz_image_get_size_fn_7202727c(fz_context* arg0, fz_image* arg1) {
	return fzImageGetSizeFn7202727C(arg0, arg1);
}

void fz_shade_prepare_fn_6a663594(fz_context* ctx, void* arg, fz_vertex* v, float* c) {
	fzShadePrepareFn6A663594(ctx, arg, v, c);
}

void fz_shade_process_fn_7e13ccea(fz_context* ctx, void* arg, fz_vertex* av, fz_vertex* bv, fz_vertex* cv) {
	fzShadeProcessFn7E13CCEA(ctx, arg, av, bv, cv);
}

fz_font* fz_load_system_font_fn_cf2c657(fz_context* ctx, char* name, int bold, int italic, int needs_exact_metrics) {
	return fzLoadSystemFontFnCF2C657(ctx, name, bold, italic, needs_exact_metrics);
}

fz_font* fz_load_system_cjk_font_fn_b491fed9(fz_context* ctx, char* name, int ros, int serif) {
	return fzLoadSystemCjkFontFnB491FED9(ctx, name, ros, serif);
}

fz_font* fz_load_system_fallback_font_fn_36cb0cb(fz_context* ctx, int script, int language, int serif, int bold, int italic) {
	return fzLoadSystemFallbackFontFn36CB0CB(ctx, script, language, serif, bold, italic);
}

fz_cmm_instance* fz_cmm_new_instance_fn_3bc12687(fz_context* ctx) {
	return fzCmmNewInstanceFn3BC12687(ctx);
}

void fz_cmm_drop_instance_fn_8fce668(fz_cmm_instance* instance) {
	fzCmmDropInstanceFn8FCE668(instance);
}

void fz_cmm_transform_pixmap_fn_a9ad9719(fz_cmm_instance* ctx, fz_icclink* link, fz_pixmap* dst, fz_pixmap* src) {
	fzCmmTransformPixmapFnA9AD9719(ctx, link, dst, src);
}

void fz_cmm_transform_color_fn_1cd2d69f(fz_cmm_instance* ctx, fz_icclink* link, unsigned short int* dst, unsigned short int* src) {
	fzCmmTransformColorFn1CD2D69F(ctx, link, dst, src);
}

void fz_cmm_init_link_fn_2c234a07(fz_cmm_instance* ctx, fz_icclink* link, fz_iccprofile* dst, int dst_extras, fz_iccprofile* src, int src_extras, fz_iccprofile* prf, fz_color_params* rend, int cmm_flags, int num_bytes, int copy_spots) {
	fzCmmInitLinkFn2C234A07(ctx, link, dst, dst_extras, src, src_extras, prf, rend, cmm_flags, num_bytes, copy_spots);
}

void fz_cmm_fin_link_fn_2b624a1a(fz_cmm_instance* ctx, fz_icclink* link) {
	fzCmmFinLinkFn2B624A1A(ctx, link);
}

void fz_cmm_init_profile_fn_5d5a5731(fz_cmm_instance* ctx, fz_iccprofile* profile) {
	fzCmmInitProfileFn5D5A5731(ctx, profile);
}

void fz_cmm_fin_profile_fn_487f1613(fz_cmm_instance* ctx, fz_iccprofile* profile) {
	fzCmmFinProfileFn487F1613(ctx, profile);
}

void fz_document_drop_fn_199b99e3(fz_context* ctx, fz_document* doc) {
	fzDocumentDropFn199B99E3(ctx, doc);
}

int fz_document_needs_password_fn_7840f251(fz_context* ctx, fz_document* doc) {
	return fzDocumentNeedsPasswordFn7840F251(ctx, doc);
}

int fz_document_authenticate_password_fn_ccf5e3d(fz_context* ctx, fz_document* doc, char* password) {
	return fzDocumentAuthenticatePasswordFnCCF5E3D(ctx, doc, password);
}

int fz_document_has_permission_fn_64826a68(fz_context* ctx, fz_document* doc, fz_permission permission) {
	return fzDocumentHasPermissionFn64826A68(ctx, doc, permission);
}

fz_outline* fz_document_load_outline_fn_ae85b015(fz_context* ctx, fz_document* doc) {
	return fzDocumentLoadOutlineFnAE85B015(ctx, doc);
}

void fz_document_layout_fn_cf5eaaa9(fz_context* ctx, fz_document* doc, float w, float h, float em) {
	fzDocumentLayoutFnCF5EAAA9(ctx, doc, w, h, em);
}

int fz_document_resolve_link_fn_f25a9656(fz_context* ctx, fz_document* doc, char* uri, float* xp, float* yp) {
	return fzDocumentResolveLinkFnF25A9656(ctx, doc, uri, xp, yp);
}

int fz_document_count_pages_fn_20f867e7(fz_context* ctx, fz_document* doc) {
	return fzDocumentCountPagesFn20F867E7(ctx, doc);
}

fz_page* fz_document_load_page_fn_a32c9877(fz_context* ctx, fz_document* doc, int number) {
	return fzDocumentLoadPageFnA32C9877(ctx, doc, number);
}

int fz_document_lookup_metadata_fn_1f9b8013(fz_context* ctx, fz_document* doc, char* key, char* buf, int size) {
	return fzDocumentLookupMetadataFn1F9B8013(ctx, doc, key, buf, size);
}

fz_colorspace* fz_document_output_intent_fn_3e3b0bcf(fz_context* ctx, fz_document* doc) {
	return fzDocumentOutputIntentFn3E3B0BCF(ctx, doc);
}

long int fz_document_make_bookmark_fn_cd7a2755(fz_context* ctx, fz_document* doc, int page) {
	return fzDocumentMakeBookmarkFnCD7A2755(ctx, doc, page);
}

int fz_document_lookup_bookmark_fn_5171746f(fz_context* ctx, fz_document* doc, long int mark) {
	return fzDocumentLookupBookmarkFn5171746F(ctx, doc, mark);
}

void fz_page_drop_page_fn_e86ad7c7(fz_context* ctx, fz_page* page) {
	fzPageDropPageFnE86AD7C7(ctx, page);
}

fz_rect* fz_page_bound_page_fn_a77bc5ed(fz_context* ctx, fz_page* page, fz_rect* arg2) {
	return fzPageBoundPageFnA77BC5ED(ctx, page, arg2);
}

void fz_page_run_page_contents_fn_7710be3e(fz_context* ctx, fz_page* page, fz_device* dev, fz_matrix* transform, fz_cookie* cookie) {
	fzPageRunPageContentsFn7710BE3E(ctx, page, dev, transform, cookie);
}

fz_link* fz_page_load_links_fn_40246ac6(fz_context* ctx, fz_page* page) {
	return fzPageLoadLinksFn40246AC6(ctx, page);
}

fz_annot* fz_page_first_annot_fn_96bf83a2(fz_context* ctx, fz_page* page) {
	return fzPageFirstAnnotFn96BF83A2(ctx, page);
}

fz_transition* fz_page_page_presentation_fn_4c62d63f(fz_context* ctx, fz_page* page, fz_transition* transition, float* duration) {
	return fzPagePagePresentationFn4C62D63F(ctx, page, transition, duration);
}

void fz_page_control_separation_fn_a66789c6(fz_context* ctx, fz_page* page, int separation, int disable) {
	fzPageControlSeparationFnA66789C6(ctx, page, separation, disable);
}

int fz_page_separation_disabled_fn_6286727e(fz_context* ctx, fz_page* page, int separation) {
	return fzPageSeparationDisabledFn6286727E(ctx, page, separation);
}

fz_separations* fz_page_separations_fn_854f23a7(fz_context* ctx, fz_page* page) {
	return fzPageSeparationsFn854F23A7(ctx, page);
}

void fz_annot_drop_fn_30a53795(fz_context* ctx, fz_annot* annot) {
	fzAnnotDropFn30A53795(ctx, annot);
}

fz_annot* fz_annot_next_fn_d7a4863d(fz_context* ctx, fz_annot* annot) {
	return fzAnnotNextFnD7A4863D(ctx, annot);
}

fz_rect* fz_annot_bound_fn_81efb60e(fz_context* ctx, fz_annot* annot, fz_rect* rect) {
	return fzAnnotBoundFn81EFB60E(ctx, annot, rect);
}

void fz_annot_run_fn_f3ff5201(fz_context* ctx, fz_annot* annot, fz_device* dev, fz_matrix* transform, fz_cookie* cookie) {
	fzAnnotRunFnF3FF5201(ctx, annot, dev, transform, cookie);
}

fz_document* fz_document_open_fn_ac22541f(fz_context* ctx, char* filename) {
	return fzDocumentOpenFnAC22541F(ctx, filename);
}

fz_document* fz_document_open_with_stream_fn_d625d461(fz_context* ctx, fz_stream* stream) {
	return fzDocumentOpenWithStreamFnD625D461(ctx, stream);
}

int fz_document_recognize_fn_37e0cef4(fz_context* ctx, char* magic) {
	return fzDocumentRecognizeFn37E0CEF4(ctx, magic);
}

fz_device* fz_document_writer_begin_page_fn_67284625(fz_context* ctx, fz_document_writer* wri, fz_rect* mediabox) {
	return fzDocumentWriterBeginPageFn67284625(ctx, wri, mediabox);
}

void fz_document_writer_end_page_fn_c982f24f(fz_context* ctx, fz_document_writer* wri, fz_device* dev) {
	fzDocumentWriterEndPageFnC982F24F(ctx, wri, dev);
}

void fz_document_writer_close_writer_fn_383baadd(fz_context* ctx, fz_document_writer* wri) {
	fzDocumentWriterCloseWriterFn383BAADD(ctx, wri);
}

void fz_document_writer_drop_writer_fn_2ac1eb31(fz_context* ctx, fz_document_writer* wri) {
	fzDocumentWriterDropWriterFn2AC1EB31(ctx, wri);
}

void fz_write_header_fn_60d0d497(fz_context* ctx, fz_band_writer* writer, fz_colorspace* cs) {
	fzWriteHeaderFn60D0D497(ctx, writer, cs);
}

void fz_write_band_fn_64127b36(fz_context* ctx, fz_band_writer* writer, int stride, int band_start, int band_height, unsigned char* samples) {
	fzWriteBandFn64127B36(ctx, writer, stride, band_start, band_height, samples);
}

void fz_write_trailer_fn_c6136351(fz_context* ctx, fz_band_writer* writer) {
	fzWriteTrailerFnC6136351(ctx, writer);
}

void fz_drop_band_writer_fn_6b3f033f(fz_context* ctx, fz_band_writer* writer) {
	fzDropBandWriterFn6B3F033F(ctx, writer);
}

void pdf_doc_event_cb_d9608017(fz_context* ctx, pdf_document* doc, pdf_doc_event* event, void* data) {
	pDFDocEventCbD9608017(ctx, doc, event, data);
}

void pdf_page_contents_process_fn_7f179711(fz_context* ctx, fz_buffer* buffer, pdf_obj* res, void* arg) {
	pDFPageContentsProcessFn7F179711(ctx, buffer, res, arg);
}

