// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Oct 2017 18:52:59 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

package mupdf

/*
#include "mupdf/pdf.h"
#include "mupdf/fitz.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Version as defined in fitz/version.h:4
	Version = "1.11"
	// PlottersG as defined in fitz/config.h:87
	PlottersG = 1
	// PlottersRgb as defined in fitz/config.h:91
	PlottersRgb = 1
	// PlottersCmyk as defined in fitz/config.h:95
	PlottersCmyk = 1
	// PlottersN as defined in fitz/config.h:99
	PlottersN = 1
	// EnablePdf as defined in fitz/config.h:109
	EnablePdf = 1
	// EnableXps as defined in fitz/config.h:113
	EnableXps = 1
	// EnableSvg as defined in fitz/config.h:117
	EnableSvg = 1
	// EnableCbz as defined in fitz/config.h:121
	EnableCbz = 1
	// EnableImg as defined in fitz/config.h:125
	EnableImg = 1
	// EnableTiff as defined in fitz/config.h:129
	EnableTiff = 1
	// EnableHtml as defined in fitz/config.h:133
	EnableHtml = 1
	// EnableEpub as defined in fitz/config.h:137
	EnableEpub = 1
	// EnableGprf as defined in fitz/config.h:141
	EnableGprf = 0
	// EnableJpx as defined in fitz/config.h:145
	EnableJpx = 1
	// EnableJs as defined in fitz/config.h:149
	EnableJs = 1
	// Pi as defined in fitz/system.h:51
	Pi = 3.1415927
	// Radian as defined in fitz/system.h:52
	Radian = 57.29578
	// Degree as defined in fitz/system.h:53
	Degree = 0.017453292
	// Sqrt2 as defined in fitz/system.h:54
	Sqrt2 = 1.4142135
	// Ln2 as defined in fitz/system.h:55
	Ln2 = 0.6931472
	// JmpBuf as defined in fitz/system.h:92
	JmpBuf = 0
	// SeekSet as defined in fitz/system.h:96
	SeekSet = 0
	// SeekCur as defined in fitz/system.h:97
	SeekCur = 1
	// SeekEnd as defined in fitz/system.h:98
	SeekEnd = 2
	// Remove as defined in fitz/system.h:209
	Remove = 0
	// OffMax as defined in fitz/system.h:223
	OffMax = 2147483647
	// Fopen as defined in fitz/system.h:225
	Fopen = 0
	// Fseek as defined in fitz/system.h:227
	Fseek = 0
	// Ftell as defined in fitz/system.h:228
	Ftell = 0
	// AtooImp as defined in fitz/system.h:229
	AtooImp = 0
	// FmtZu as defined in fitz/system.h:243
	FmtZu = "%zu"
	// AesDecrypt as defined in fitz/crypt.h:105
	AesDecrypt = 0
	// AesEncrypt as defined in fitz/crypt.h:106
	AesEncrypt = 1
	// ReplacementCharacter as defined in fitz/string-util.h:7
	ReplacementCharacter = 65533
	// MetaFormat as defined in fitz/document.h:591
	MetaFormat = "format"
	// MetaEncryption as defined in fitz/document.h:592
	MetaEncryption = "encryption"
	// MetaInfoAuthor as defined in fitz/document.h:594
	MetaInfoAuthor = "info:Author"
	// MetaInfoTitle as defined in fitz/document.h:595
	MetaInfoTitle = "info:Title"
	// MrangeCap as defined in pdf/cmap.h:13
	MrangeCap = 8
)

// BidiDirection as declared in fitz/bidi.h:31
type BidiDirection int32

// BidiDirection enumeration from fitz/bidi.h:31
const (
	BidiLtr     BidiDirection = iota
	BidiRtl     BidiDirection = 1
	BidiNeutral BidiDirection = 2
)

// BidiFlags as declared in fitz/bidi.h:38
type BidiFlags int32

// BidiFlags enumeration from fitz/bidi.h:38
const (
	BidiClassifyWhiteSpace BidiFlags = 1
	BidiReplaceTab         BidiFlags = 2
)

// Linecap as declared in fitz/path.h:26
type Linecap int32

// Linecap enumeration from fitz/path.h:26
const (
	LinecapButt     Linecap = iota
	LinecapRound    Linecap = 1
	LinecapSquare   Linecap = 2
	LinecapTriangle Linecap = 3
)

// Linejoin as declared in fitz/path.h:34
type Linejoin int32

// Linejoin enumeration from fitz/path.h:34
const (
	LinejoinMiter    Linejoin = iota
	LinejoinRound    Linejoin = 1
	LinejoinBevel    Linejoin = 2
	LinejoinMiterXps Linejoin = 3
)

// TextLanguage as declared in fitz/text.h:46
type TextLanguage int32

// TextLanguage enumeration from fitz/text.h:46
const (
	LangUnset  TextLanguage = iota
	LangUr     TextLanguage = 507
	LangUrd    TextLanguage = 3423
	LangKo     TextLanguage = 416
	LangJa     TextLanguage = 37
	LangZh     TextLanguage = 242
	LangZhHans TextLanguage = 14093
	LangZhHant TextLanguage = 14822
)

// SeparationBehavior as declared in fitz/separation.h:32
type SeparationBehavior int32

// SeparationBehavior enumeration from fitz/separation.h:32
const (
	SeparationComposite SeparationBehavior = iota
	SeparationSpot      SeparationBehavior = 1
	SeparationDisabled  SeparationBehavior = 2
)

// Permission as declared in fitz/document.h:29
type Permission int32

// Permission enumeration from fitz/document.h:29
const (
	PermissionPrint    Permission = 112
	PermissionCopy     Permission = 99
	PermissionEdit     Permission = 101
	PermissionAnnotate Permission = 110
)

// LayerConfigUiType as declared in pdf/document.h:231
type LayerConfigUiType int32

// LayerConfigUiType enumeration from pdf/document.h:231
const (
	LayerUiLabel    LayerConfigUiType = iota
	LayerUiCheckbox LayerConfigUiType = 1
	LayerUiRadiobox LayerConfigUiType = 2
)

// PortfolioSchemaType as declared in pdf/document.h:297
type PortfolioSchemaType int32

// PortfolioSchemaType enumeration from pdf/document.h:297
const (
	SchemaNumber       PortfolioSchemaType = iota
	SchemaSize         PortfolioSchemaType = 1
	SchemaText         PortfolioSchemaType = 2
	SchemaDate         PortfolioSchemaType = 3
	SchemaDesc         PortfolioSchemaType = 4
	SchemaModdate      PortfolioSchemaType = 5
	SchemaCreationdate PortfolioSchemaType = 6
	SchemaFilename     PortfolioSchemaType = 7
	SchemaUnknown      PortfolioSchemaType = 8
)

// Token as declared in pdf/parse.h:20
type Token int32

// Token enumeration from pdf/parse.h:20
const (
	TokError      Token = iota
	TokEof        Token = 1
	TokOpenArray  Token = 2
	TokCloseArray Token = 3
	TokOpenDict   Token = 4
	TokCloseDict  Token = 5
	TokOpenBrace  Token = 6
	TokCloseBrace Token = 7
	TokName       Token = 8
	TokInt        Token = 9
	TokReal       Token = 10
	TokString     Token = 11
	TokKeyword    Token = 12
	TokR          Token = 13
	TokTrue       Token = 14
	TokFalse      Token = 15
	TokNull       Token = 16
	TokObj        Token = 17
	TokEndobj     Token = 18
	TokStream     Token = 19
	TokEndstream  Token = 20
	TokXref       Token = 21
	TokTrailer    Token = 22
	TokStartxref  Token = 23
	NumTokens     Token = 24
)

// AnnotType as declared in pdf/annot.h:32
type AnnotType int32

// AnnotType enumeration from pdf/annot.h:32
const (
	AnnotText           AnnotType = iota
	AnnotLink           AnnotType = 1
	AnnotFreeText       AnnotType = 2
	AnnotLine           AnnotType = 3
	AnnotSquare         AnnotType = 4
	AnnotCircle         AnnotType = 5
	AnnotPolygon        AnnotType = 6
	AnnotPolyLine       AnnotType = 7
	AnnotHighlight      AnnotType = 8
	AnnotUnderline      AnnotType = 9
	AnnotSquiggly       AnnotType = 10
	AnnotStrikeOut      AnnotType = 11
	AnnotStamp          AnnotType = 12
	AnnotCaret          AnnotType = 13
	AnnotInk            AnnotType = 14
	AnnotPopup          AnnotType = 15
	AnnotFileAttachment AnnotType = 16
	AnnotSound          AnnotType = 17
	AnnotMovie          AnnotType = 18
	AnnotWidget         AnnotType = 19
	AnnotScreen         AnnotType = 20
	AnnotPrinterMark    AnnotType = 21
	AnnotTrapNet        AnnotType = 22
	AnnotWatermark      AnnotType = 23
	Annot3d             AnnotType = 24
	AnnotUnknown        AnnotType = -1
)

const (
	// ErrorNone as declared in fitz/context.h:91
	ErrorNone = iota
	// ErrorMemory as declared in fitz/context.h:92
	ErrorMemory = 1
	// ErrorGeneric as declared in fitz/context.h:93
	ErrorGeneric = 2
	// ErrorSyntax as declared in fitz/context.h:94
	ErrorSyntax = 3
	// ErrorTrylater as declared in fitz/context.h:95
	ErrorTrylater = 4
	// ErrorAbort as declared in fitz/context.h:96
	ErrorAbort = 5
	// ErrorCount as declared in fitz/context.h:97
	ErrorCount = 6
)

const (
	// StoreUnlimited as declared in fitz/context.h:141
	StoreUnlimited = iota
	// StoreDefault as declared in fitz/context.h:142
	StoreDefault = 268435456
)

const (
	// LockAlloc as declared in fitz/context.h:385
	LockAlloc = iota
	// LockFreetype as declared in fitz/context.h:386
	LockFreetype = 1
	// LockGlyphcache as declared in fitz/context.h:387
	LockGlyphcache = 2
	// LockMax as declared in fitz/context.h:388
	LockMax = 3
)

const (
	// Utfmax as declared in fitz/string-util.h:93
	Utfmax = 4
)

const (
	// StreamMetaProgressive as declared in fitz/stream.h:200
	StreamMetaProgressive = 1
	// StreamMetaLength as declared in fitz/stream.h:201
	StreamMetaLength = 2
)

const (
	// ImageUnknown as declared in fitz/compressed-buffer.h:20
	ImageUnknown = iota
	// ImageRaw as declared in fitz/compressed-buffer.h:23
	ImageRaw = 1
	// ImageFax as declared in fitz/compressed-buffer.h:26
	ImageFax = 2
	// ImageFlate as declared in fitz/compressed-buffer.h:27
	ImageFlate = 3
	// ImageLzw as declared in fitz/compressed-buffer.h:28
	ImageLzw = 4
	// ImageRld as declared in fitz/compressed-buffer.h:29
	ImageRld = 5
	// ImageBmp as declared in fitz/compressed-buffer.h:32
	ImageBmp = 6
	// ImageGif as declared in fitz/compressed-buffer.h:33
	ImageGif = 7
	// ImageJpeg as declared in fitz/compressed-buffer.h:34
	ImageJpeg = 8
	// ImageJpx as declared in fitz/compressed-buffer.h:35
	ImageJpx = 9
	// ImageJxr as declared in fitz/compressed-buffer.h:36
	ImageJxr = 10
	// ImagePng as declared in fitz/compressed-buffer.h:37
	ImagePng = 11
	// ImagePnm as declared in fitz/compressed-buffer.h:38
	ImagePnm = 12
	// ImageTiff as declared in fitz/compressed-buffer.h:39
	ImageTiff = 13
)

const (
	// MaxColors as declared in fitz/colorspace.h:8
	MaxColors = 32
)

const (
	// RiPerceptual as declared in fitz/colorspace.h:13
	RiPerceptual = iota
	// RiRelativeColorimetric as declared in fitz/colorspace.h:14
	RiRelativeColorimetric = 1
	// RiSaturation as declared in fitz/colorspace.h:15
	RiSaturation = 2
	// RiAbsoluteColorimetric as declared in fitz/colorspace.h:16
	RiAbsoluteColorimetric = 3
)

const (
	// PixmapFlagInterpolate as declared in fitz/pixmap.h:357
	PixmapFlagInterpolate = 1
	// PixmapFlagFreeSamples as declared in fitz/pixmap.h:358
	PixmapFlagFreeSamples = 2
)

const (
	// MaxSeparations as declared in fitz/separation.h:17
	MaxSeparations = 64
)

const (
	// FunctionBased as declared in fitz/shade.h:18
	FunctionBased = 1
	// Linear as declared in fitz/shade.h:19
	Linear = 2
	// Radial as declared in fitz/shade.h:20
	Radial = 3
	// MeshType4 as declared in fitz/shade.h:21
	MeshType4 = 4
	// MeshType5 as declared in fitz/shade.h:22
	MeshType5 = 5
	// MeshType6 as declared in fitz/shade.h:23
	MeshType6 = 6
	// MeshType7 as declared in fitz/shade.h:24
	MeshType7 = 7
)

const (
	// AdobeCns1 as declared in fitz/font.h:58
	AdobeCns1 = iota
	// AdobeGb1 as declared in fitz/font.h:58
	AdobeGb1 = 1
	// AdobeJapan1 as declared in fitz/font.h:58
	AdobeJapan1 = 2
	// AdobeKorea1 as declared in fitz/font.h:58
	AdobeKorea1 = 3
)

const (
	// DevflagMask as declared in fitz/device.h:29
	DevflagMask = 1
	// DevflagColor as declared in fitz/device.h:30
	DevflagColor = 2
	// DevflagUncacheable as declared in fitz/device.h:31
	DevflagUncacheable = 4
	// DevflagFillcolorUndefined as declared in fitz/device.h:32
	DevflagFillcolorUndefined = 8
	// DevflagStrokecolorUndefined as declared in fitz/device.h:33
	DevflagStrokecolorUndefined = 16
	// DevflagStartcapUndefined as declared in fitz/device.h:34
	DevflagStartcapUndefined = 32
	// DevflagDashcapUndefined as declared in fitz/device.h:35
	DevflagDashcapUndefined = 64
	// DevflagEndcapUndefined as declared in fitz/device.h:36
	DevflagEndcapUndefined = 128
	// DevflagLinejoinUndefined as declared in fitz/device.h:37
	DevflagLinejoinUndefined = 256
	// DevflagMiterlimitUndefined as declared in fitz/device.h:38
	DevflagMiterlimitUndefined = 512
	// DevflagLinewidthUndefined as declared in fitz/device.h:39
	DevflagLinewidthUndefined = 1024
	// DevflagBboxDefined as declared in fitz/device.h:43
	DevflagBboxDefined = 2048
	// DevflagGridfitAsTiled as declared in fitz/device.h:44
	DevflagGridfitAsTiled = 4096
)

const (
	// BlendNormal as declared in fitz/device.h:50
	BlendNormal = iota
	// BlendMultiply as declared in fitz/device.h:51
	BlendMultiply = 1
	// BlendScreen as declared in fitz/device.h:52
	BlendScreen = 2
	// BlendOverlay as declared in fitz/device.h:53
	BlendOverlay = 3
	// BlendDarken as declared in fitz/device.h:54
	BlendDarken = 4
	// BlendLighten as declared in fitz/device.h:55
	BlendLighten = 5
	// BlendColorDodge as declared in fitz/device.h:56
	BlendColorDodge = 6
	// BlendColorBurn as declared in fitz/device.h:57
	BlendColorBurn = 7
	// BlendHardLight as declared in fitz/device.h:58
	BlendHardLight = 8
	// BlendSoftLight as declared in fitz/device.h:59
	BlendSoftLight = 9
	// BlendDifference as declared in fitz/device.h:60
	BlendDifference = 10
	// BlendExclusion as declared in fitz/device.h:61
	BlendExclusion = 11
	// BlendHue as declared in fitz/device.h:64
	BlendHue = 12
	// BlendSaturation as declared in fitz/device.h:65
	BlendSaturation = 13
	// BlendColor as declared in fitz/device.h:66
	BlendColor = 14
	// BlendLuminosity as declared in fitz/device.h:67
	BlendLuminosity = 15
	// BlendModemask as declared in fitz/device.h:70
	BlendModemask = 15
	// BlendIsolated as declared in fitz/device.h:71
	BlendIsolated = 16
	// BlendKnockout as declared in fitz/device.h:72
	BlendKnockout = 32
)

const (
	// DontInterpolateImages as declared in fitz/device.h:193
	DontInterpolateImages = 1
	// MaintainContainerStack as declared in fitz/device.h:194
	MaintainContainerStack = 2
	// NoCache as declared in fitz/device.h:195
	NoCache = 4
)

const (
	// TestOptImages as declared in fitz/device.h:306
	TestOptImages = 1
	// TestOptShadings as declared in fitz/device.h:310
	TestOptShadings = 2
)

// DrawOptionsUsage as declared in fitz/device.h:362
var DrawOptionsUsage string

const (
	// StextPreserveLigatures as declared in fitz/structured-text.h:43
	StextPreserveLigatures = 1
	// StextPreserveWhitespace as declared in fitz/structured-text.h:44
	StextPreserveWhitespace = 2
	// StextPreserveImages as declared in fitz/structured-text.h:45
	StextPreserveImages = 4
)

const (
	// StextBlockText as declared in fitz/structured-text.h:60
	StextBlockText = iota
	// StextBlockImage as declared in fitz/structured-text.h:61
	StextBlockImage = 1
)

// StextOptionsUsage as declared in fitz/structured-text.h:104
var StextOptionsUsage string

const (
	// TransitionNone as declared in fitz/transition.h:11
	TransitionNone = iota
	// TransitionSplit as declared in fitz/transition.h:12
	TransitionSplit = 1
	// TransitionBlinds as declared in fitz/transition.h:13
	TransitionBlinds = 2
	// TransitionBox as declared in fitz/transition.h:14
	TransitionBox = 3
	// TransitionWipe as declared in fitz/transition.h:15
	TransitionWipe = 4
	// TransitionDissolve as declared in fitz/transition.h:16
	TransitionDissolve = 5
	// TransitionGlitter as declared in fitz/transition.h:17
	TransitionGlitter = 6
	// TransitionFly as declared in fitz/transition.h:18
	TransitionFly = 7
	// TransitionPush as declared in fitz/transition.h:19
	TransitionPush = 8
	// TransitionCover as declared in fitz/transition.h:20
	TransitionCover = 9
	// TransitionUncover as declared in fitz/transition.h:21
	TransitionUncover = 10
	// TransitionFade as declared in fitz/transition.h:22
	TransitionFade = 11
)

// _WriteOptionsUsage as declared in fitz/writer.h:152
var _WriteOptionsUsage string

// SvgWriteOptionsUsage as declared in fitz/writer.h:153
var SvgWriteOptionsUsage string

// PclWriteOptionsUsage as declared in fitz/writer.h:155
var PclWriteOptionsUsage string

// PwgWriteOptionsUsage as declared in fitz/writer.h:156
var PwgWriteOptionsUsage string

const (
	// SvgTextAsPath as declared in fitz/output-svg.h:10
	SvgTextAsPath = iota
	// SvgTextAsText as declared in fitz/output-svg.h:11
	SvgTextAsText = 1
)

const ()

const (
	// LexbufSmall as declared in pdf/document.h:19
	LexbufSmall = 256
	// LexbufLarge as declared in pdf/document.h:20
	LexbufLarge = 65536
)

const ()

const (
	// PageIncompleteContents as declared in pdf/page.h:200
	PageIncompleteContents = 1
	// PageIncompleteAnnots as declared in pdf/page.h:201
	PageIncompleteAnnots = 2
)

const (
	// FdFixedPitch as declared in pdf/font.h:10
	FdFixedPitch = 1
	// FdSerif as declared in pdf/font.h:11
	FdSerif = 2
	// FdSymbolic as declared in pdf/font.h:12
	FdSymbolic = 4
	// FdScript as declared in pdf/font.h:13
	FdScript = 8
	// FdNonsymbolic as declared in pdf/font.h:14
	FdNonsymbolic = 32
	// FdItalic as declared in pdf/font.h:15
	FdItalic = 64
	// FdAllCap as declared in pdf/font.h:16
	FdAllCap = 65536
	// FdSmallCap as declared in pdf/font.h:17
	FdSmallCap = 131072
	// FdForceBold as declared in pdf/font.h:18
	FdForceBold = 262144
)

// DocEncoding as declared in pdf/font.h:25
var DocEncoding [256]uint16

// MacRoman as declared in pdf/font.h:26
var MacRoman [256]string

// MacExpert as declared in pdf/font.h:27
var MacExpert [256]string

// WinAnsi as declared in pdf/font.h:28
var WinAnsi [256]string

// Standard as declared in pdf/font.h:29
var Standard [256]string

const (
	// AnnotIsInvisible as declared in pdf/annot.h:39
	AnnotIsInvisible = 1
	// AnnotIsHidden as declared in pdf/annot.h:40
	AnnotIsHidden = 2
	// AnnotIsPrint as declared in pdf/annot.h:41
	AnnotIsPrint = 4
	// AnnotIsNoZoom as declared in pdf/annot.h:42
	AnnotIsNoZoom = 8
	// AnnotIsNoRotate as declared in pdf/annot.h:43
	AnnotIsNoRotate = 16
	// AnnotIsNoView as declared in pdf/annot.h:44
	AnnotIsNoView = 32
	// AnnotIsReadOnly as declared in pdf/annot.h:45
	AnnotIsReadOnly = 64
	// AnnotIsLocked as declared in pdf/annot.h:46
	AnnotIsLocked = 128
	// AnnotIsToggleNoView as declared in pdf/annot.h:47
	AnnotIsToggleNoView = 256
	// AnnotIsLockedContents as declared in pdf/annot.h:48
	AnnotIsLockedContents = 512
)

const (
	// AnnotLineEndingNone as declared in pdf/annot.h:53
	AnnotLineEndingNone = iota
	// AnnotLineEndingSquare as declared in pdf/annot.h:54
	AnnotLineEndingSquare = 1
	// AnnotLineEndingCircle as declared in pdf/annot.h:55
	AnnotLineEndingCircle = 2
	// AnnotLineEndingDiamond as declared in pdf/annot.h:56
	AnnotLineEndingDiamond = 3
	// AnnotLineEndingOpenarrow as declared in pdf/annot.h:57
	AnnotLineEndingOpenarrow = 4
	// AnnotLineEndingClosedarrow as declared in pdf/annot.h:58
	AnnotLineEndingClosedarrow = 5
	// AnnotLineEndingButt as declared in pdf/annot.h:59
	AnnotLineEndingButt = 6
	// AnnotLineEndingRopenarrow as declared in pdf/annot.h:60
	AnnotLineEndingRopenarrow = 7
	// AnnotLineEndingRclosedarrow as declared in pdf/annot.h:61
	AnnotLineEndingRclosedarrow = 8
	// AnnotLineEndingSlash as declared in pdf/annot.h:62
	AnnotLineEndingSlash = 9
)

const ()

const (
	// WidgetTypeNotWidget as declared in pdf/widget.h:7
	WidgetTypeNotWidget = -1
	// WidgetTypePushbutton as declared in pdf/widget.h:8
	WidgetTypePushbutton = 0
	// WidgetTypeCheckbox as declared in pdf/widget.h:9
	WidgetTypeCheckbox = 1
	// WidgetTypeRadiobutton as declared in pdf/widget.h:10
	WidgetTypeRadiobutton = 2
	// WidgetTypeText as declared in pdf/widget.h:11
	WidgetTypeText = 3
	// WidgetTypeListbox as declared in pdf/widget.h:12
	WidgetTypeListbox = 4
	// WidgetTypeCombobox as declared in pdf/widget.h:13
	WidgetTypeCombobox = 5
	// WidgetTypeSignature as declared in pdf/widget.h:14
	WidgetTypeSignature = 6
)

const (
	// WidgetContentUnrestrained as declared in pdf/widget.h:20
	WidgetContentUnrestrained = iota
	// WidgetContentNumber as declared in pdf/widget.h:21
	WidgetContentNumber = 1
	// WidgetContentSpecial as declared in pdf/widget.h:22
	WidgetContentSpecial = 2
	// WidgetContentDate as declared in pdf/widget.h:23
	WidgetContentDate = 3
	// WidgetContentTime as declared in pdf/widget.h:24
	WidgetContentTime = 4
)

const ()

const (
	// EventTypePointer as declared in pdf/event.h:13
	EventTypePointer = iota
)

const (
	// PointerDown as declared in pdf/event.h:19
	PointerDown = iota
	// PointerUp as declared in pdf/event.h:20
	PointerUp = 1
)

const (
	// DocumentEventAlert as declared in pdf/event.h:69
	DocumentEventAlert = iota
	// DocumentEventPrint as declared in pdf/event.h:70
	DocumentEventPrint = 1
	// DocumentEventLaunchUrl as declared in pdf/event.h:71
	DocumentEventLaunchUrl = 2
	// DocumentEventMailDoc as declared in pdf/event.h:72
	DocumentEventMailDoc = 3
	// DocumentEventSubmit as declared in pdf/event.h:73
	DocumentEventSubmit = 4
	// DocumentEventExecMenuItem as declared in pdf/event.h:74
	DocumentEventExecMenuItem = 5
	// DocumentEventExecDialog as declared in pdf/event.h:75
	DocumentEventExecDialog = 6
)

const (
	// AlertIconError as declared in pdf/event.h:113
	AlertIconError = iota
	// AlertIconWarning as declared in pdf/event.h:114
	AlertIconWarning = 1
	// AlertIconQuestion as declared in pdf/event.h:115
	AlertIconQuestion = 2
	// AlertIconStatus as declared in pdf/event.h:116
	AlertIconStatus = 3
)

const (
	// AlertButtonGroupOk as declared in pdf/event.h:122
	AlertButtonGroupOk = iota
	// AlertButtonGroupOkCancel as declared in pdf/event.h:123
	AlertButtonGroupOkCancel = 1
	// AlertButtonGroupYesNo as declared in pdf/event.h:124
	AlertButtonGroupYesNo = 2
	// AlertButtonGroupYesNoCancel as declared in pdf/event.h:125
	AlertButtonGroupYesNoCancel = 3
)

const (
	// AlertButtonNone as declared in pdf/event.h:131
	AlertButtonNone = iota
	// AlertButtonOk as declared in pdf/event.h:132
	AlertButtonOk = 1
	// AlertButtonCancel as declared in pdf/event.h:133
	AlertButtonCancel = 2
	// AlertButtonNo as declared in pdf/event.h:134
	AlertButtonNo = 3
	// AlertButtonYes as declared in pdf/event.h:135
	AlertButtonYes = 4
)
