// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 11 Oct 2017 01:43:23 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package mupdf provides Go bindings.
*/
package mupdf
