// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Oct 2017 18:52:59 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package mupdf provides Go bindings.
*/
package mupdf
