// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 11 Oct 2017 01:43:23 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

package mupdf

/*
#include "mupdf/pdf.h"
#include "mupdf/fitz.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// FzOff type as declared in fitz/system.h:222
type FzOff int32

// File as declared in include/stdio.h:153
type File C.FILE

// FzAllocContext as declared in fitz/context.h:12
type FzAllocContext C.fz_alloc_context

// FzErrorContext as declared in fitz/context.h:13
type FzErrorContext C.fz_error_context

// FzErrorStackSlot as declared in fitz/context.h:14
type FzErrorStackSlot C.fz_error_stack_slot

// FzIdContext as declared in fitz/context.h:15
type FzIdContext C.fz_id_context

// FzWarnContext as declared in fitz/context.h:16
type FzWarnContext C.fz_warn_context

// FzFontContext as declared in fitz/context.h:17
type FzFontContext C.fz_font_context

// FzColorspaceContext as declared in fitz/context.h:18
type FzColorspaceContext C.fz_colorspace_context

// FzCmmEngine as declared in fitz/context.h:19
type FzCmmEngine C.fz_cmm_engine

// FzCmmInstance as declared in fitz/context.h:20
type FzCmmInstance C.fz_cmm_instance

// FzAaContext as declared in fitz/context.h:21
type FzAaContext C.fz_aa_context

// FzStyleContext as declared in fitz/context.h:22
type FzStyleContext C.fz_style_context

// FzLocksContext as declared in fitz/context.h:23
type FzLocksContext C.fz_locks_context

// FzTuningContext as declared in fitz/context.h:24
type FzTuningContext C.fz_tuning_context

// FzStore as declared in fitz/context.h:25
type FzStore C.fz_store

// FzGlyphCache as declared in fitz/context.h:26
type FzGlyphCache C.fz_glyph_cache

// FzDocumentHandlerContext as declared in fitz/context.h:27
type FzDocumentHandlerContext C.fz_document_handler_context

// FzOutputContext as declared in fitz/context.h:28
type FzOutputContext C.fz_output_context

// FzContext as declared in fitz/context.h:29
type FzContext C.fz_context

// FzTuneImageDecodeFn type as declared in fitz/context.h:237
type FzTuneImageDecodeFn func(arg unsafe.Pointer, w int32, h int32, l2factor int32, subarea []FzIrect)

// FzTuneImageScaleFn type as declared in fitz/context.h:253
type FzTuneImageScaleFn func(arg unsafe.Pointer, dstW int32, dstH int32, srcW int32, srcH int32) int32

// FzPoint as declared in fitz/geometry.h:123
type FzPoint C.fz_point

// FzRect as declared in fitz/geometry.h:147
type FzRect C.fz_rect

// FzIrect as declared in fitz/geometry.h:175
type FzIrect C.fz_irect

// FzMatrix as declared in fitz/geometry.h:262
type FzMatrix C.fz_matrix

// FzMd5 as declared in fitz/crypt.h:14
type FzMd5 C.fz_md5

// FzSha256 as declared in fitz/crypt.h:33
type FzSha256 C.fz_sha256

// FzSha512 as declared in fitz/crypt.h:55
type FzSha512 C.fz_sha512

// FzSha384 as declared in fitz/crypt.h:77
type FzSha384 C.fz_sha384

// FzArc4 as declared in fitz/crypt.h:85
type FzArc4 C.fz_arc4

// FzAes as declared in fitz/crypt.h:103
type FzAes C.fz_aes

// FzHashTable as declared in fitz/hash.h:20
type FzHashTable C.fz_hash_table

// FzHashTableDropFn type as declared in fitz/hash.h:21
type FzHashTableDropFn func(ctx *FzContext, val unsafe.Pointer)

// FzHashTableForEachFn type as declared in fitz/hash.h:22
type FzHashTableForEachFn func(ctx *FzContext, state unsafe.Pointer, key unsafe.Pointer, keylen int32, val unsafe.Pointer)

// FzOutput as declared in fitz/output.h:13
type FzOutput C.fz_output

// FzOutputWriteFn type as declared in fitz/output.h:26
type FzOutputWriteFn func(ctx *FzContext, state unsafe.Pointer, data unsafe.Pointer, n uint)

// FzOutputSeekFn type as declared in fitz/output.h:37
type FzOutputSeekFn func(ctx *FzContext, state unsafe.Pointer, offset FzOff, whence int32)

// FzOutputTellFn type as declared in fitz/output.h:48
type FzOutputTellFn func(ctx *FzContext, state unsafe.Pointer) FzOff

// FzOutputCloseFn type as declared in fitz/output.h:58
type FzOutputCloseFn func(ctx *FzContext, state unsafe.Pointer)

// FzBuffer as declared in fitz/buffer.h:13
type FzBuffer C.fz_buffer

// FzPool as declared in fitz/pool.h:7
type FzPool C.fz_pool

// FzTree as declared in fitz/tree.h:11
type FzTree C.fz_tree

// FzBidiFragmentFn type as declared in fitz/bidi.h:53
type FzBidiFragmentFn func(fragment *uint32, fragmentlen uint, bidilevel int32, script int32, arg unsafe.Pointer)

// FzXml as declared in fitz/xml.h:11
type FzXml C.fz_xml

// FzStream as declared in fitz/stream.h:22
type FzStream C.fz_stream

// FzStreamNextFn type as declared in fitz/stream.h:239
type FzStreamNextFn func(ctx *FzContext, stm *FzStream, max uint) int32

// FzStreamCloseFn type as declared in fitz/stream.h:249
type FzStreamCloseFn func(ctx *FzContext, state unsafe.Pointer)

// FzStreamSeekFn type as declared in fitz/stream.h:259
type FzStreamSeekFn func(ctx *FzContext, stm *FzStream, offset FzOff, whence int32)

// FzStreamMetaFn type as declared in fitz/stream.h:269
type FzStreamMetaFn func(ctx *FzContext, stm *FzStream, key int32, size int32, ptr unsafe.Pointer) int32

// FzCompressionParams as declared in fitz/compressed-buffer.h:9
type FzCompressionParams C.fz_compression_params

// FzCompressedBuffer as declared in fitz/compressed-buffer.h:11
type FzCompressedBuffer C.fz_compressed_buffer

// FzJbig2Globals as declared in fitz/filter.h:10
type FzJbig2Globals C.fz_jbig2_globals

// FzStorable as declared in fitz/store.h:29
type FzStorable C.fz_storable

// FzKeyStorable as declared in fitz/store.h:30
type FzKeyStorable C.fz_key_storable

// FzStoreDropFn type as declared in fitz/store.h:32
type FzStoreDropFn func(arg0 *FzContext, arg1 *FzStorable)

// FzStoreHash as declared in fitz/store.h:151
type FzStoreHash C.fz_store_hash

// FzStoreType as declared in fitz/store.h:161
type FzStoreType C.fz_store_type

// FzStoreFilterFn type as declared in fitz/store.h:260
type FzStoreFilterFn func(ctx *FzContext, arg unsafe.Pointer, key unsafe.Pointer) int32

// FzArchive as declared in fitz/archive.h:9
type FzArchive C.fz_archive

// FzZipWriter as declared in fitz/archive.h:181
type FzZipWriter C.fz_zip_writer

// FzColorParams as declared in fitz/colorspace.h:19
type FzColorParams C.fz_color_params

// FzColorspace as declared in fitz/colorspace.h:40
type FzColorspace C.fz_colorspace

// FzIccprofile as declared in fitz/colorspace.h:47
type FzIccprofile C.fz_iccprofile

// FzIcclink as declared in fitz/colorspace.h:52
type FzIcclink C.fz_icclink

// FzDefaultColorspaces as declared in fitz/colorspace.h:57
type FzDefaultColorspaces C.fz_default_colorspaces

// FzColorspaceConvertFn type as declared in fitz/colorspace.h:103
type FzColorspaceConvertFn func(ctx *FzContext, cs *FzColorspace, src []float32, dst []float32)

// FzColorspaceDestructFn type as declared in fitz/colorspace.h:105
type FzColorspaceDestructFn func(ctx *FzContext, cs *FzColorspace)

// FzColorspaceBaseFn type as declared in fitz/colorspace.h:107
type FzColorspaceBaseFn func(cs *FzColorspace) *FzColorspace

// FzColorspaceClampFn type as declared in fitz/colorspace.h:109
type FzColorspaceClampFn func(cs *FzColorspace, src *float32, dst []float32)

// FzColorConverter as declared in fitz/colorspace.h:130
type FzColorConverter C.fz_color_converter

// FzCalColorspace as declared in fitz/colorspace.h:153
type FzCalColorspace C.fz_cal_colorspace

// FzPixmap as declared in fitz/pixmap.h:17
type FzPixmap struct {
	Storable       FzStorable
	X              int32
	Y              int32
	W              int32
	H              int32
	N              byte
	S              byte
	Alpha          byte
	Flags          byte
	Stride         int32
	Seps           *FzSeparations
	Xres           int32
	Yres           int32
	Colorspace     *FzColorspace
	Samples        []byte
	ref7c1a1ba1    *C.fz_pixmap
	allocs7c1a1ba1 interface{}
}

// FzScaleCache as declared in fitz/pixmap.h:370
type FzScaleCache C.fz_scale_cache

// FzPixmapConverter type as declared in fitz/pixmap.h:388
type FzPixmapConverter func(ctx *FzContext, dp *FzPixmap, sp []FzPixmap, prf []FzColorspace, defaultCs []FzDefaultColorspaces, colorParams []FzColorParams, copySpots int32)

// FzSeparations as declared in fitz/separation.h:20
type FzSeparations C.fz_separations

// FzGlyph as declared in fitz/glyph.h:14
type FzGlyph C.fz_glyph

// FzBitmap as declared in fitz/bitmap.h:13
type FzBitmap C.fz_bitmap

// FzHalftone as declared in fitz/bitmap.h:39
type FzHalftone C.fz_halftone

// FzImage as declared in fitz/image.h:20
type FzImage C.fz_image

// FzCompressedImage as declared in fitz/image.h:21
type FzCompressedImage C.fz_compressed_image

// FzPixmapImage as declared in fitz/image.h:22
type FzPixmapImage C.fz_pixmap_image

// FzDropImageFn type as declared in fitz/image.h:72
type FzDropImageFn func(ctx *FzContext, image *FzImage)

// FzImageGetPixmapFn type as declared in fitz/image.h:97
type FzImageGetPixmapFn func(ctx *FzContext, im *FzImage, subarea []FzIrect, w int32, h int32, l2factor []int32) *FzPixmap

// FzImageGetSizeFn type as declared in fitz/image.h:105
type FzImageGetSizeFn func(arg0 *FzContext, arg1 *FzImage) uint

// FzShade as declared in fitz/shade.h:80
type FzShade C.fz_shade

// FzVertex as declared in fitz/shade.h:141
type FzVertex C.fz_vertex

// FzShadePrepareFn type as declared in fitz/shade.h:159
type FzShadePrepareFn func(ctx *FzContext, arg unsafe.Pointer, v []FzVertex, c []float32)

// FzShadeProcessFn type as declared in fitz/shade.h:171
type FzShadeProcessFn func(ctx *FzContext, arg unsafe.Pointer, av []FzVertex, bv []FzVertex, cv []FzVertex)

// FzFont as declared in fitz/font.h:15
type FzFont C.fz_font

// FzFontFlags as declared in fitz/font.h:78
type FzFontFlags C.fz_font_flags_t

// FzShaperData as declared in fitz/font.h:104
type FzShaperData C.fz_shaper_data_t

// FzLoadSystemFontFn type as declared in fitz/font.h:167
type FzLoadSystemFontFn func(ctx *FzContext, name string, bold int32, italic int32, needsExactMetrics int32) *FzFont

// FzLoadSystemCjkFontFn type as declared in fitz/font.h:178
type FzLoadSystemCjkFontFn func(ctx *FzContext, name string, ros int32, serif int32) *FzFont

// FzLoadSystemFallbackFontFn type as declared in fitz/font.h:190
type FzLoadSystemFallbackFontFn func(ctx *FzContext, script int32, language int32, serif int32, bold int32, italic int32) *FzFont

// FzPath as declared in fitz/path.h:17
type FzPath C.fz_path

// FzStrokeState as declared in fitz/path.h:18
type FzStrokeState C.fz_stroke_state

// FzPathWalker as declared in fitz/path.h:60
type FzPathWalker C.fz_path_walker

// FzText as declared in fitz/text.h:22
type FzText C.fz_text

// FzTextSpan as declared in fitz/text.h:23
type FzTextSpan C.fz_text_span

// FzTextItem as declared in fitz/text.h:24
type FzTextItem C.fz_text_item

// FzCmmNewInstanceFn type as declared in fitz/color-management.h:24
type FzCmmNewInstanceFn func(ctx *FzContext) *FzCmmInstance

// FzCmmDropInstanceFn type as declared in fitz/color-management.h:31
type FzCmmDropInstanceFn func(instance *FzCmmInstance)

// FzCmmTransformPixmapFn type as declared in fitz/color-management.h:37
type FzCmmTransformPixmapFn func(ctx *FzCmmInstance, link *FzIcclink, dst []FzPixmap, src []FzPixmap)

// FzCmmTransformColorFn type as declared in fitz/color-management.h:43
type FzCmmTransformColorFn func(ctx *FzCmmInstance, link *FzIcclink, dst []uint16, src []uint16)

// FzCmmInitLinkFn type as declared in fitz/color-management.h:48
type FzCmmInitLinkFn func(ctx *FzCmmInstance, link *FzIcclink, dst []FzIccprofile, dstExtras int32, src []FzIccprofile, srcExtras int32, prf []FzIccprofile, rend []FzColorParams, cmmFlags int32, numBytes int32, copySpots int32)

// FzCmmFinLinkFn type as declared in fitz/color-management.h:53
type FzCmmFinLinkFn func(ctx *FzCmmInstance, link *FzIcclink)

// FzCmmInitProfileFn type as declared in fitz/color-management.h:59
type FzCmmInitProfileFn func(ctx *FzCmmInstance, profile *FzIccprofile)

// FzCmmFinProfileFn type as declared in fitz/color-management.h:65
type FzCmmFinProfileFn func(ctx *FzCmmInstance, profile *FzIccprofile)

// FzDevice as declared in fitz/device.h:24
type FzDevice C.fz_device

// FzDeviceContainerStack as declared in fitz/device.h:78
type FzDeviceContainerStack C.fz_device_container_stack

// FzCookie as declared in fitz/device.h:202
type FzCookie C.fz_cookie

// FzDrawOptions as declared in fitz/device.h:347
type FzDrawOptions C.fz_draw_options

// FzDisplayList as declared in fitz/display-list.h:25
type FzDisplayList C.fz_display_list

// FzStextChar as declared in fitz/structured-text.h:19
type FzStextChar C.fz_stext_char

// FzStextLine as declared in fitz/structured-text.h:20
type FzStextLine C.fz_stext_line

// FzStextBlock as declared in fitz/structured-text.h:21
type FzStextBlock C.fz_stext_block

// FzStextPage as declared in fitz/structured-text.h:22
type FzStextPage C.fz_stext_page

// FzStextOptions as declared in fitz/structured-text.h:170
type FzStextOptions C.fz_stext_options

// FzTransition as declared in fitz/transition.h:8
type FzTransition C.fz_transition

// FzLink as declared in fitz/link.h:12
type FzLink C.fz_link

// FzOutline as declared in fitz/outline.h:31
type FzOutline C.fz_outline

// FzDocument as declared in fitz/document.h:16
type FzDocument C.fz_document

// FzDocumentHandler as declared in fitz/document.h:17
type FzDocumentHandler C.fz_document_handler

// FzPage as declared in fitz/document.h:18
type FzPage C.fz_page

// FzAnnot as declared in fitz/document.h:19
type FzAnnot C.fz_annot

// FzBookmark type as declared in fitz/document.h:20
type FzBookmark int

// FzDocumentDropFn type as declared in fitz/document.h:38
type FzDocumentDropFn func(ctx *FzContext, doc *FzDocument)

// FzDocumentNeedsPasswordFn type as declared in fitz/document.h:45
type FzDocumentNeedsPasswordFn func(ctx *FzContext, doc *FzDocument) int32

// FzDocumentAuthenticatePasswordFn type as declared in fitz/document.h:52
type FzDocumentAuthenticatePasswordFn func(ctx *FzContext, doc *FzDocument, password string) int32

// FzDocumentHasPermissionFn type as declared in fitz/document.h:59
type FzDocumentHasPermissionFn func(ctx *FzContext, doc *FzDocument, permission FzPermission) int32

// FzDocumentLoadOutlineFn type as declared in fitz/document.h:66
type FzDocumentLoadOutlineFn func(ctx *FzContext, doc *FzDocument) *FzOutline

// FzDocumentLayoutFn type as declared in fitz/document.h:72
type FzDocumentLayoutFn func(ctx *FzContext, doc *FzDocument, w float32, h float32, em float32)

// FzDocumentResolveLinkFn type as declared in fitz/document.h:79
type FzDocumentResolveLinkFn func(ctx *FzContext, doc *FzDocument, uri string, xp []float32, yp []float32) int32

// FzDocumentCountPagesFn type as declared in fitz/document.h:86
type FzDocumentCountPagesFn func(ctx *FzContext, doc *FzDocument) int32

// FzDocumentLoadPageFn type as declared in fitz/document.h:92
type FzDocumentLoadPageFn func(ctx *FzContext, doc *FzDocument, number int32) *FzPage

// FzDocumentLookupMetadataFn type as declared in fitz/document.h:99
type FzDocumentLookupMetadataFn func(ctx *FzContext, doc *FzDocument, key string, buf []byte, size int32) int32

// FzDocumentOutputIntentFn type as declared in fitz/document.h:104
type FzDocumentOutputIntentFn func(ctx *FzContext, doc *FzDocument) *FzColorspace

// FzDocumentMakeBookmarkFn type as declared in fitz/document.h:110
type FzDocumentMakeBookmarkFn func(ctx *FzContext, doc *FzDocument, page int32) FzBookmark

// FzDocumentLookupBookmarkFn type as declared in fitz/document.h:116
type FzDocumentLookupBookmarkFn func(ctx *FzContext, doc *FzDocument, mark FzBookmark) int32

// FzPageDropPageFn type as declared in fitz/document.h:123
type FzPageDropPageFn func(ctx *FzContext, page *FzPage)

// FzPageBoundPageFn type as declared in fitz/document.h:130
type FzPageBoundPageFn func(ctx *FzContext, page *FzPage, arg2 []FzRect) *FzRect

// FzPageRunPageContentsFn type as declared in fitz/document.h:137
type FzPageRunPageContentsFn func(ctx *FzContext, page *FzPage, dev []FzDevice, transform []FzMatrix, cookie []FzCookie)

// FzPageLoadLinksFn type as declared in fitz/document.h:143
type FzPageLoadLinksFn func(ctx *FzContext, page *FzPage) *FzLink

// FzPageFirstAnnotFn type as declared in fitz/document.h:150
type FzPageFirstAnnotFn func(ctx *FzContext, page *FzPage) *FzAnnot

// FzPagePagePresentationFn type as declared in fitz/document.h:158
type FzPagePagePresentationFn func(ctx *FzContext, page *FzPage, transition []FzTransition, duration []float32) *FzTransition

// FzPageControlSeparationFn type as declared in fitz/document.h:165
type FzPageControlSeparationFn func(ctx *FzContext, page *FzPage, separation int32, disable int32)

// FzPageSeparationDisabledFn type as declared in fitz/document.h:172
type FzPageSeparationDisabledFn func(ctx *FzContext, page *FzPage, separation int32) int32

// FzPageSeparationsFn type as declared in fitz/document.h:179
type FzPageSeparationsFn func(ctx *FzContext, page *FzPage) *FzSeparations

// FzAnnotDropFn type as declared in fitz/document.h:181
type FzAnnotDropFn func(ctx *FzContext, annot *FzAnnot)

// FzAnnotNextFn type as declared in fitz/document.h:182
type FzAnnotNextFn func(ctx *FzContext, annot *FzAnnot) *FzAnnot

// FzAnnotBoundFn type as declared in fitz/document.h:183
type FzAnnotBoundFn func(ctx *FzContext, annot *FzAnnot, rect []FzRect) *FzRect

// FzAnnotRunFn type as declared in fitz/document.h:184
type FzAnnotRunFn func(ctx *FzContext, annot *FzAnnot, dev []FzDevice, transform []FzMatrix, cookie []FzCookie)

// FzDocumentOpenFn type as declared in fitz/document.h:251
type FzDocumentOpenFn func(ctx *FzContext, filename string) *FzDocument

// FzDocumentOpenWithStreamFn type as declared in fitz/document.h:262
type FzDocumentOpenWithStreamFn func(ctx *FzContext, stream *FzStream) *FzDocument

// FzDocumentRecognizeFn type as declared in fitz/document.h:275
type FzDocumentRecognizeFn func(ctx *FzContext, magic string) int32

// FzDocumentWriter as declared in fitz/writer.h:10
type FzDocumentWriter C.fz_document_writer

// FzDocumentWriterBeginPageFn type as declared in fitz/writer.h:20
type FzDocumentWriterBeginPageFn func(ctx *FzContext, wri *FzDocumentWriter, mediabox []FzRect) *FzDevice

// FzDocumentWriterEndPageFn type as declared in fitz/writer.h:28
type FzDocumentWriterEndPageFn func(ctx *FzContext, wri *FzDocumentWriter, dev []FzDevice)

// FzDocumentWriterCloseWriterFn type as declared in fitz/writer.h:37
type FzDocumentWriterCloseWriterFn func(ctx *FzContext, wri *FzDocumentWriter)

// FzDocumentWriterDropWriterFn type as declared in fitz/writer.h:48
type FzDocumentWriterDropWriterFn func(ctx *FzContext, wri *FzDocumentWriter)

// FzBandWriter as declared in fitz/band-writer.h:11
type FzBandWriter C.fz_band_writer

// FzWriteHeaderFn type as declared in fitz/band-writer.h:13
type FzWriteHeaderFn func(ctx *FzContext, writer *FzBandWriter, cs []FzColorspace)

// FzWriteBandFn type as declared in fitz/band-writer.h:14
type FzWriteBandFn func(ctx *FzContext, writer *FzBandWriter, stride int32, bandStart int32, bandHeight int32, samples string)

// FzWriteTrailerFn type as declared in fitz/band-writer.h:15
type FzWriteTrailerFn func(ctx *FzContext, writer *FzBandWriter)

// FzDropBandWriterFn type as declared in fitz/band-writer.h:16
type FzDropBandWriterFn func(ctx *FzContext, writer *FzBandWriter)

// FzPwgOptions as declared in fitz/output-pwg.h:11
type FzPwgOptions C.fz_pwg_options

// FzPclOptions as declared in fitz/output-pcl.h:14
type FzPclOptions C.fz_pcl_options

// PDFDocument as declared in pdf/object.h:4
type PDFDocument C.pdf_document

// PDFObj as declared in pdf/object.h:12
type PDFObj C.pdf_obj

// PDFLexbuf as declared in pdf/document.h:4
type PDFLexbuf C.pdf_lexbuf

// PDFLexbufLarge as declared in pdf/document.h:5
type PDFLexbufLarge C.pdf_lexbuf_large

// PDFXref as declared in pdf/document.h:6
type PDFXref C.pdf_xref

// PDFCrypt as declared in pdf/document.h:7
type PDFCrypt C.pdf_crypt

// PDFOcgDescriptor as declared in pdf/document.h:8
type PDFOcgDescriptor C.pdf_ocg_descriptor

// PDFPortfolio as declared in pdf/document.h:9
type PDFPortfolio C.pdf_portfolio

// PDFPage as declared in pdf/document.h:11
type PDFPage C.pdf_page

// PDFAnnot as declared in pdf/document.h:12
type PDFAnnot C.pdf_annot

// PDFWidget as declared in pdf/document.h:13
type PDFWidget C.pdf_widget

// PDFHotspot as declared in pdf/document.h:14
type PDFHotspot C.pdf_hotspot

// PDFJs as declared in pdf/document.h:15
type PDFJs C.pdf_js

// PDFDocEvent as declared in pdf/document.h:50
type PDFDocEvent C.pdf_doc_event

// PDFDocEventCb type as declared in pdf/document.h:56
type PDFDocEventCb func(ctx *FzContext, doc *PDFDocument, event []PDFDocEvent, data unsafe.Pointer)

// PDFLayerConfig as declared in pdf/document.h:150
type PDFLayerConfig C.pdf_layer_config

// PDFLayerConfigUi as declared in pdf/document.h:240
type PDFLayerConfigUi C.pdf_layer_config_ui

// PDFPortfolioSchema as declared in pdf/document.h:305
type PDFPortfolioSchema C.pdf_portfolio_schema

// PDFSigner as declared in pdf/document.h:539
type PDFSigner C.pdf_signer

// PDFUnsavedSig as declared in pdf/document.h:542
type PDFUnsavedSig C.pdf_unsaved_sig

// PDFRevPageMap as declared in pdf/document.h:555
type PDFRevPageMap C.pdf_rev_page_map

// PDFGraftMap as declared in pdf/document.h:682
type PDFGraftMap C.pdf_graft_map

// PDFWriteOptions as declared in pdf/document.h:828
type PDFWriteOptions C.pdf_write_options

// PDFXrefEntry as declared in pdf/xref.h:36
type PDFXrefEntry C.pdf_xref_entry

// PDFXrefSubsec as declared in pdf/xref.h:55
type PDFXrefSubsec C.pdf_xref_subsec

// PDFDesignatedName as declared in pdf/crypt.h:32
type PDFDesignatedName C.pdf_designated_name

// PDFPageContentsProcessFn type as declared in pdf/page.h:115
type PDFPageContentsProcessFn func(ctx *FzContext, buffer *FzBuffer, res []PDFObj, arg unsafe.Pointer)

// PDFFunction as declared in pdf/resource.h:30
type PDFFunction C.pdf_function

// PDFPattern as declared in pdf/resource.h:55
type PDFPattern C.pdf_pattern

// PDFXobject as declared in pdf/resource.h:79
type PDFXobject C.pdf_xobject

// PDFCmap as declared in pdf/cmap.h:8
type PDFCmap C.pdf_cmap

// PDFRange as declared in pdf/cmap.h:9
type PDFRange C.pdf_range

// PDFXrange as declared in pdf/cmap.h:10
type PDFXrange C.pdf_xrange

// PDFMrange as declared in pdf/cmap.h:11
type PDFMrange C.pdf_mrange

// PDFFontDesc as declared in pdf/font.h:31
type PDFFontDesc C.pdf_font_desc

// PDFHmtx as declared in pdf/font.h:32
type PDFHmtx C.pdf_hmtx

// PDFVmtx as declared in pdf/font.h:33
type PDFVmtx C.pdf_vmtx

// PDFCsi as declared in pdf/interpret.h:4
type PDFCsi C.pdf_csi

// PDFGstate as declared in pdf/interpret.h:5
type PDFGstate C.pdf_gstate

// PDFProcessor as declared in pdf/interpret.h:6
type PDFProcessor C.pdf_processor

// PDFDaInfo as declared in pdf/appearance.h:10
type PDFDaInfo C.pdf_da_info

// PDFUiEvent as declared in pdf/event.h:37
type PDFUiEvent C.pdf_ui_event

// PDFAlertEvent as declared in pdf/event.h:108
type PDFAlertEvent C.pdf_alert_event

// PDFSubmitEvent as declared in pdf/event.h:163
type PDFSubmitEvent C.pdf_submit_event

// PDFLaunchUrlEvent as declared in pdf/event.h:180
type PDFLaunchUrlEvent C.pdf_launch_url_event

// PDFMailDocEvent as declared in pdf/event.h:202
type PDFMailDocEvent C.pdf_mail_doc_event

// PDFJsEvent as declared in pdf/javascript.h:9
type PDFJsEvent C.pdf_js_event
